namespace ExpenseTracker
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Represents a single expense entry tracked by the ExpenseTracker application.
    /// This model holds the expense's unique identifier, date, amount, category,
    /// optional description, currency code, business flag, and creation/update timestamps.
    /// Returns the expense details for display and reporting purposes.
    /// </summary>
    public class Expense
    {
        /// <summary>
        /// Unique identifier for the expense entry. Generated by default using <see cref="Guid.NewGuid"/>.
        /// </summary>
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Date when the expense occurred. Defaults to the current UTC date.
        /// </summary>
        [Required]
        public DateOnly Date { get; set; } = DateOnly.FromDateTime(DateTime.UtcNow);

        /// <summary>
        /// Monetary amount of the expense. Must be non-negative.
        /// </summary>
        [Required]
        [Range(0.0, double.MaxValue)]
        public decimal Amount { get; set; }

       
        /// <summary>
        /// Optional detailed description of the expense. Maximum length is 500 characters.
        /// </summary>
        [StringLength(500)]
        public string? Description { get; set; }

        /// <summary>
        /// ISO currency code for the expense amount (3 characters). Defaults to "USD".
        /// </summary>
        [StringLength(3)]
        public string Currency { get; set; } = "USD";

       /// <summary>
       /// Gets or sets a value indicating whether the current instance represents a business entity.
       /// </summary>
       /// <remarks>This property is used to differentiate between business and non-business entities
       /// within the application context.</remarks>
        public bool IsBusiness { get; set; } = false;

        /// <summary>
        /// UTC timestamp when the expense record was created. Set to current UTC time by default.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// UTC timestamp when the expense record was last updated. Null if never updated.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }
    }

    /// <summary>
    /// Represents a category for expenses. Each category has a unique identifier and a name.
    /// </summary>
    public class Category
    {
        /// <summary>
        /// Unique identifier for the category. Generated by default using <see cref="Guid.NewGuid"/>.
        /// </summary>
        [Key]
        public int Id { get; set; } 

        /// <summary>
        /// Name of the category. Maximum length is 100 characters.
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Collection of expenses associated with this category.
        /// </summary>
        public ICollection<Expense> Expenses { get; set; } = new List<Expense>();
    }
    

}